### ISSUE TITLE
Retornar data original da transação de cartão de crédito da Nubank

### ISSUE THREAD

**Issue by hugobarauna** [pluggyai/meu-pluggy#1]
Agumas semanas atrás quando testei a Pluggy para puxar as transações do cartão de crédito, funcionou bem. Porém senti falta de uma coisa.

A data que é retornada para cada transação do cartão de crédito é a data que aparece na fatura, não a data original de quando foi feita a transação. Para o meu caso de uso, eu precisaria da data original da transação.

Gostaria de pedir para adicionar esse campo.

Obrigado

**Comment by Gabrielpanga** [comment]
Adicionado o campo.

Para mais informações consulte nossa documentação:

https://docs.pluggy.ai/docs/transactions#transaction-credit-card-metadata-schema

**Comment by tavlima** [comment]
@Gabrielpanga, já houve algum release do SDK Node com esse novo campo? Não consegui encontrar... 🤔

**Comment by Gabrielpanga** [comment]
@tavlima , acabamos de enviar a nova versão do Node com os campos!
