### ISSUE TITLE
"Meu Pluggy" desativado na lista de connector

### ISSUE THREAD

**Issue by adrianoresende** [pluggyai/meu-pluggy#10]
Olá!

Estava seguindo passo a passo no readme, porém não estou conseguindo selecionar Meu Pluggy na lista de connector.

<img width="255" alt="image" src="https://github.com/user-attachments/assets/070333aa-a5a2-431e-af4f-c8caa141db5a">

O que é preciso para liberar?

**Comment by Gabrielpanga** [comment]
Para utilizar meu Pluggy, você deve se registrar com um e-mail e ativar dentro do período de trial. Pode nos compartilhar seu e-mail pelo Discord para que possamos estender o trial e configurar corretamente em seu time!

Todos os times que utilizam meu Pluggy têm o trial para realizar essa configuração
