### ISSUE TITLE
Transações da conta Nubank

### ISSUE THREAD

**Issue by jeffbzrr** [pluggyai/meu-pluggy#2]
Antes de tudo, obrigado a Pluggy por abrir essa porta e libertar esse dados. Eu usava a anos o excelente pynubank até acontecer os problemas recentes e daí fiquei no escuro em relação meus gastos.

Para o Nubank eu recebo "executionStatus": "PARTIAL_SUCCESS", e só consigo acessar os dados do cartão de crédito. Eu vi que ele retorna como UNSTABLE e que em https://status.pluggy.ai/ tem tb uma observação.

No entanto, no "Meu Pluggy", eu consigo ver transações recentes da conta, tem alguma maneira de recuperar essas transações da conta do nubank?

**Comment by Gabrielpanga** [comment]
Olá jeffersonmsb, isso mesmo, a conexão pela qual você conectou a conta está instável. Somente a conexão através do meupluggy funciona corretamente.

Se você seguir os passos discutidos no leia-me principal do repositório você poderá consultar a conta conectada ao seu client_id & secret.
