### ISSUE TITLE
Frequência de atualização

### ISSUE THREAD

**Issue by jeffbzrr** [pluggyai/meu-pluggy#3]
Olá, qual a frequência de atualização a partir do meupluggy?

Não sei se entendi errado no leia-me que seria diariamente. Conexão do Nubank está como 2 dias atrás. Eu tb tentei atualizar o item mas acredito que não seja esse o caminho.

**Comment by Gabrielpanga** [comment]
Olá, todas as conexões são atualizadas a cada 24 horas.
Sua conexão específica já deve estar sincronizada e atualizada todos os dias.
