### ISSUE TITLE
SDK Python

### ISSUE THREAD

**Issue by diraol** [pluggyai/meu-pluggy#7]
Olá pessoal, tudo bem?

Vocês tem algum plano ou expectativa de lançar o SDK Python da API de vocês?

Aliás, não sei como tem sido o processo de desenvolvimento, mas se vocês especificarem a API usando OpenAPI vocês podem usar o [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) para gerar os SDKs/Clients para diversas linguagens. :)

**Comment by Gabrielpanga** [comment]
Vamos publicar nosso OAS que temos de forma privada para gerar automaticamente os SDKs, planejamos fazê-lo em curto prazo e sincronizá-lo automaticamente com o privado.

**Comment by diraol** [comment]
Notícia incrível!
Só para eu me planejar aqui, alguma previsão? Uma semana, duas semanas, um mês, dois meses? (Dois dias.... Hehehe)

**Comment by NicolasMontone** [comment]
> Notícia incrível! Só para eu me planejar aqui, alguma previsão? Uma semana, duas semanas, um mês, dois meses? (Dois dias.... Hehehe)

Iremos publicá-lo entre esta semana e a próxima 🥇 Muito obrigado!

**Comment by diraol** [comment]
Oi @NicolasMontone :)
Alguma novidade?

**Comment by Gabrielpanga** [comment]
Oi @diraol , Já está disponível: https://api.pluggy.ai/oas3.json

**Comment by diraol** [comment]
Só compartilhando aqui que o SDK foi publicado no pypi como pluggy_sdk e que ele será atualizado de forma automática 1x por semana.

**Comment by diraol** [comment]
https://pypi.org/project/pluggy-sdk/
