### ISSUE TITLE
Integração com banco Neon

### ISSUE THREAD

**Issue by cl3t0** [pluggyai/meu-pluggy#9]
Quando me deparei com a plataforma fiquei maravilhado!! Gostei demais. O único problema é que não tem integração com o banco que tenho mais limite de cartão, o banco Neon. Essa inclusão está no roadmap? É possível? Desde já obrigado!

**Comment by NicolasMontone** [comment]
Oi Tudo bem? Muito obrigado pelo relatório!

Vi que o banco é participante do Open Finance, mas nosso provedor ainda não oferece suporte, já pedi para que o fizessem!

Manterei você informado e avisarei quando eles tiverem suporte para o banco :)

**Comment by cl3t0** [comment]
Obrigado @NicolasMontone! Com o banco Neon inserido já vou ter uma visão muito melhor das minhas finanças.

Conectei minha conta Nubank. Gostaria de saber se é possível baixar todas as minhas transações. Vi um botão de download que me permite baixar um relatório mas ele veio com apenas duas linhas na tabela. Uma pra minha conta e outra pro meu cartão. Queria ter acesso as transações diretamente, num CSV. É possível via UI? Se não, é possível via API?

Obrigado novamente pela atenção!

**Comment by NicolasMontone** [comment]
Hey @cl3t0 , não é possível via UI, mas poderemos adicioná-lo no futuro!
Gostaria de saber seu caso de uso também se quiser que tenhamos um discord onde possamos conversar (https://discord.gg/EanrwJADby).

Por outro lado, via API você pode fazer um GET para todas as suas transações e fazer um script que as exporte para você via formato CSV
